name: iot_isra_app
description: "A new Flutter project." 
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.5.4

 
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  dio: ^5.2.1+1
  uuid: ^4.2.2
  logger: ^2.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

 
flutter:
 
  uses-material-design: true
 
  assets:
    - assets/images/
 
